import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
       
        <div className={styles.imgdiv}>
        <img className={styles.myimg} src="/coder img.avif" width={300} height={300} alt="Hunting coder"></img>
        </div>
        <h1>
          &lt;Hunting Coder/&gt;
        </h1>
        <div>
          <h2>Latest Blogs</h2>
          <div className={styles.blog_items}>
          <h3>Lets learn Javascript</h3>
          <p>JavaScript is a versatile programming language commonly used.....</p>
          </div>
          <div className={styles.blog_items}>
          <h3>Lets learn MongoDB</h3>
          <p>MongoDB is a popular, open-source, NoSQL database management...</p>
          </div>
          <div className={styles.blog_items}>
          <h3>Lets learn Nodejs</h3>
          <p>Node.js is a powerful, open-source, cross-platform JavaScript....</p>
          </div>
        </div>

        
      </main>
    </>
  );
}
